apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: kanban-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: kanban-pod
  type: LoadBalancer
status:
  loadBalancer: {}